[window]
decorations = "Full"
opacity = 1.0

[window.dimensions]
columns = 100
lines = 85

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [{ key = "Return", mods = "Alt", action = "ToggleFullscreen" }]

[env]
TERM = "alacritty-direct"
